--------------------------------------------------------
-- Archivo creado  - martes-abril-22-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table E11EVENSTORE_CLIENTES
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."E11EVENSTORE_CLIENTES" 
   (	"RUT" NVARCHAR2(12), 
	"NOMBRE" NVARCHAR2(200), 
	"APELLIDOS" NVARCHAR2(200), 
	"USUARIO" NVARCHAR2(150), 
	"EMAIL" NVARCHAR2(254), 
	"CLAVE" NVARCHAR2(128), 
	"FECHANACIMIENTO" DATE, 
	"DIRECCION" NVARCHAR2(255)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.E11EVENSTORE_CLIENTES
SET DEFINE OFF;
Insert into SYSTEM.E11EVENSTORE_CLIENTES (RUT,NOMBRE,APELLIDOS,USUARIO,EMAIL,CLAVE,FECHANACIMIENTO,DIRECCION) values ('24555444-3','DANIEL','MUNOZ','DANIEL21','DA.MUNOZ@GMAIL.COM','DANIEL123',to_date('17/04/99','DD/MM/RR'),null);
Insert into SYSTEM.E11EVENSTORE_CLIENTES (RUT,NOMBRE,APELLIDOS,USUARIO,EMAIL,CLAVE,FECHANACIMIENTO,DIRECCION) values ('15801477-5','Alejandra Camila','Nuñez Gilberto','Alejandra2105','alejandra.nu@gmail.com','Alejandra2105',to_date('21/05/91','DD/MM/RR'),'Catedral 1310, depto 101, Santiago');
Insert into SYSTEM.E11EVENSTORE_CLIENTES (RUT,NOMBRE,APELLIDOS,USUARIO,EMAIL,CLAVE,FECHANACIMIENTO,DIRECCION) values ('16801477-5','ALEJANDRA','PEREZ','ALEJANDRA22','ALEJAPE@GMAIL.COM','A123456',to_date('19/04/95','DD/MM/RR'),'CALLE LAS CALILAS 55');
Insert into SYSTEM.E11EVENSTORE_CLIENTES (RUT,NOMBRE,APELLIDOS,USUARIO,EMAIL,CLAVE,FECHANACIMIENTO,DIRECCION) values ('10316874-8','MANUEL','GUERRERO','MANUEL55','DANI_GUERRERO@GMAIL.COM','D123456',to_date('08/09/89','DD/MM/RR'),null);
--------------------------------------------------------
--  DDL for Index SYS_C008439
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008439" ON "SYSTEM"."E11EVENSTORE_CLIENTES" ("RUT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C008440
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008440" ON "SYSTEM"."E11EVENSTORE_CLIENTES" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table E11EVENSTORE_CLIENTES
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."E11EVENSTORE_CLIENTES" MODIFY ("RUT" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."E11EVENSTORE_CLIENTES" MODIFY ("FECHANACIMIENTO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."E11EVENSTORE_CLIENTES" ADD PRIMARY KEY ("RUT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."E11EVENSTORE_CLIENTES" ADD UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
