--------------------------------------------------------
-- Archivo creado  - martes-abril-22-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table E11EVENSTORE_PRODUCTO
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."E11EVENSTORE_PRODUCTO" 
   (	"ID" NUMBER(19,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOMBRE" NVARCHAR2(100), 
	"PRECIO" NUMBER(11,0), 
	"CATEGORIA" NVARCHAR2(50), 
	"IMAGEN" NVARCHAR2(200) DEFAULT NULL, 
	"STOCK" NUMBER(11,0), 
	"DESCRIPCION" NVARCHAR2(500)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.E11EVENSTORE_PRODUCTO
SET DEFINE OFF;
Insert into SYSTEM.E11EVENSTORE_PRODUCTO (ID,NOMBRE,PRECIO,CATEGORIA,IMAGEN,STOCK,DESCRIPCION) values ('42','Need For Speed Unbound','20990','CAT_1-Carreras','https://www.todojuegos.cl/Productos/_mediaProd/29406/nfsunbucfhico.jpg','9','sta última adición a la franquicia Need for Speed de Criterion Games ofrece campañas de un jugador y multijugador, con carreras electrizantes llenas de adrenalina');
Insert into SYSTEM.E11EVENSTORE_PRODUCTO (ID,NOMBRE,PRECIO,CATEGORIA,IMAGEN,STOCK,DESCRIPCION) values ('25','Assassins Creed Mirage','49990','CAT_5-Accion','https://m.media-amazon.com/images/I/81XTMj3qhPL._SL1500_.jpg','9','En esta ocasion encarnamos a Basim, un joven ladron callejero al que acompañamos en su periplo para convertirse en un maestro de los Asesinos. Desarrollado por Ubisoft Bordeaux, su historia nos lleva a la ciudad de Bagdad del siglo IX, para descubrir nuestro pasado y acabar con la amenaza de los miembros de la Orden que controlan la ciudad');
Insert into SYSTEM.E11EVENSTORE_PRODUCTO (ID,NOMBRE,PRECIO,CATEGORIA,IMAGEN,STOCK,DESCRIPCION) values ('41','Street Fighter 6','39990','CAT_5-Accion','https://preview.redd.it/street-fighter-6-box-art-leaked-v0-33j6wl0xpr4a1.png?auto=webp&s=8088b280bf4f255c5677bdc438484da0cbbff20c','6','Por primera vez, SF6 ofrece una experiencia narrativa inmersiva en constante evolucion que le da poder al jugador para crear su propio Guerrero Mundial y participar verdaderamente en el Universo Street Fighter. SF6 proporciona la experiencia de lucha estandar para que los profesionales tanto ocasionales como probados en batalla puedan disfrutar en los años venideros');
Insert into SYSTEM.E11EVENSTORE_PRODUCTO (ID,NOMBRE,PRECIO,CATEGORIA,IMAGEN,STOCK,DESCRIPCION) values ('43','The Crew Motorfest','59990','CAT_1-Carreras','https://cdn.mobygames.com/covers/17647229-the-crew-motorfest-playstation-5-front-cover.jpg','4','Compite en carreras emocionantes y eventos temáticos en este paraíso automovilístico con cientos de vehículos legendarios');
Insert into SYSTEM.E11EVENSTORE_PRODUCTO (ID,NOMBRE,PRECIO,CATEGORIA,IMAGEN,STOCK,DESCRIPCION) values ('45','Counter Strike','0','CAT_4-Free to play','https://shared.fastly.steamstatic.com//store_item_assets/steam/apps/1222670/4bcb26e78354f1789d2af48258e9054dd3ca5043/capsule_616x353_alt_assets_7_spanish.jpg?t=1740506448','10','Durante las dos últimas décadas, Counter Strike ha proporcionado una experiencia competitiva de primer nivel para los millones de jugadores de todo el mundo que contribuyeron a darle forma.');
Insert into SYSTEM.E11EVENSTORE_PRODUCTO (ID,NOMBRE,PRECIO,CATEGORIA,IMAGEN,STOCK,DESCRIPCION) values ('46','Sims 4','0','CAT_4-Free to play','https://shared.fastly.steamstatic.com//store_item_assets/steam/apps/1222670/4bcb26e78354f1789d2af48258e9054dd3ca5043/capsule_616x353_alt_assets_7_spanish.jpg?t=1740506448','10','¡Crea un mundo único de Sims a tu imagen y semejanza! Crea y personaliza Sims, construye casas increíbles y juega a la vida. Amplía tu juego con packs y kits para descubrir más moda, decoración, profesiones y más.');
Insert into SYSTEM.E11EVENSTORE_PRODUCTO (ID,NOMBRE,PRECIO,CATEGORIA,IMAGEN,STOCK,DESCRIPCION) values ('47','Monster Hunter World','25990','CAT_3-Mundo abierto','https://http2.mlstatic.com/D_NQ_NP_897318-MLU70059888000_062023-O.webp','5','Monster Hunter World es el retorno de la serie a las consolas de sobremesa, permitiéndonos cazar criaturas gigantes en un entorno salvaje, ya sea en solitario o con tres cazadores con un nuevo sistema multijugador drop-in que permite cooperativo entre regiones');
Insert into SYSTEM.E11EVENSTORE_PRODUCTO (ID,NOMBRE,PRECIO,CATEGORIA,IMAGEN,STOCK,DESCRIPCION) values ('48','Grand Theft Auto V','19990','CAT_3-Mundo abierto','https://juegosdigitaleschile.com/files/images/productos/1538762676-grand-theft-auto-5-gta-v-gta-5-ps4-primaria-solo-por-hoy.jpg','18','Esta versión del éxito, más ambiciosa técnicamente, presenta gráficos y nuevo contenido como armas, vehículos o misiones, además de una banda sonora ampliada y más jugadores en el modo online');
Insert into SYSTEM.E11EVENSTORE_PRODUCTO (ID,NOMBRE,PRECIO,CATEGORIA,IMAGEN,STOCK,DESCRIPCION) values ('49','For Honor','25990','CAT_6-Supervivencia','https://juegospro.cl/cdn/shop/files/eb380427-9371-4daa-9675-75a6d71c8497.jpg?v=1728033747&width=1445','9','Ubisoft presenta con For Honor un videojuego medieval con especial énfasis en la cooperación entre varios jugadores por equipos, que destaca por sus violentos combates y poderoso apartado gráfico');
Insert into SYSTEM.E11EVENSTORE_PRODUCTO (ID,NOMBRE,PRECIO,CATEGORIA,IMAGEN,STOCK,DESCRIPCION) values ('50','Fortnite: Darkfire Bundle Switch','19990','CAT_6-Supervivencia','https://m.media-amazon.com/images/I/5177HgzL1NL._AC_UF1000,1000_QL80_.jpg','13','Fortnite es un videojuego de Epic Games que nos transporta a un mundo sandbox donde explorar, construir y sobrevivir a los peligros de la noche.');
Insert into SYSTEM.E11EVENSTORE_PRODUCTO (ID,NOMBRE,PRECIO,CATEGORIA,IMAGEN,STOCK,DESCRIPCION) values ('51','Resident Evil Revelations','19990','CAT_2-Terror','https://juegosdigitaleschile.com/files/images/productos/1503962921-resident-evil-revelations-p4.JPG','10','Resident Evil: Revelations —cuyo título original en Japón es Biohazard: Revelations —es un videojuego de terror y supervivencia de disparos en tercera persona desarrollado y publicado por Capcom y lanzado originalmente en 2012 para la consola portátil Nintendo 3DS.');
Insert into SYSTEM.E11EVENSTORE_PRODUCTO (ID,NOMBRE,PRECIO,CATEGORIA,IMAGEN,STOCK,DESCRIPCION) values ('52','Silent Hill 2 PS5','55990','CAT_2-Terror','https://i.postimg.cc/wj8pD0h9/preferable-box.jpg','5','Un remake del SILENT HILL 2 de 2001 con nuevos gráficos de avanzada que incluyen trazado de rayos. Mira el perturbador mundo de Silent Hill como nunca antes, y disfruta de una experiencia narrativa aún más inmersiva. ');
--------------------------------------------------------
--  DDL for Index SYS_C008446
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008446" ON "SYSTEM"."E11EVENSTORE_PRODUCTO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table E11EVENSTORE_PRODUCTO
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."E11EVENSTORE_PRODUCTO" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."E11EVENSTORE_PRODUCTO" MODIFY ("PRECIO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."E11EVENSTORE_PRODUCTO" MODIFY ("STOCK" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."E11EVENSTORE_PRODUCTO" ADD CHECK ("PRECIO" >= 0) ENABLE;
  ALTER TABLE "SYSTEM"."E11EVENSTORE_PRODUCTO" ADD CHECK ("STOCK" >= 0) ENABLE;
  ALTER TABLE "SYSTEM"."E11EVENSTORE_PRODUCTO" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
