# Generated by Django 5.2 on 2025-04-14 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E11evenStore', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='administrativo',
            table='E11EVENSTORE_ADMINISTRATIVOS',
        ),
        migrations.AlterModelTable(
            name='cliente',
            table='E11EVENSTORE_CLIENTES',
        ),
    ]
