# Generated by Django 5.2 on 2025-04-11 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E11evenStore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('usuario', models.CharField(max_length=150)),
                ('correo', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('contraseña', models.CharField(max_length=128)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_usuario', models.CharField(choices=[('usuario', 'Usuario'), ('admin', 'Administrativo')], max_length=10)),
            ],
        ),
    ]
