# Generated by Django 5.2 on 2025-04-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("E11evenStore", "0008_transaccionpago"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="apellidos",
            field=models.CharField(
                db_column="APELLIDOS", max_length=200, verbose_name="Apellidos"
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="clave",
            field=models.CharField(
                db_column="CLAVE", max_length=128, verbose_name="Contraseña"
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="direccion",
            field=models.CharField(
                blank=True,
                db_column="DIRECCION",
                max_length=255,
                null=True,
                verbose_name="Dirección",
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="email",
            field=models.EmailField(
                db_column="EMAIL",
                max_length=254,
                unique=True,
                verbose_name="Correo electrónico",
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="fechaNacimiento",
            field=models.DateField(
                db_column="FECHANACIMIENTO", verbose_name="Fecha de nacimiento"
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="nombre",
            field=models.CharField(
                db_column="NOMBRE", max_length=200, verbose_name="Nombres"
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="rut",
            field=models.CharField(
                db_column="RUT",
                max_length=12,
                primary_key=True,
                serialize=False,
                verbose_name="RUT",
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="usuario",
            field=models.CharField(
                db_column="USUARIO", max_length=150, verbose_name="Nombre Usuario"
            ),
        ),
    ]
