# Generated by Django 5.2 on 2025-04-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("E11evenStore", "0009_alter_cliente_apellidos_alter_cliente_clave_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="apellidos",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="clave",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="direccion",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="fechaNacimiento",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="nombre",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="rut",
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="usuario",
            field=models.CharField(max_length=150),
        ),
    ]
