# Generated by Django 5.2 on 2025-04-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("E11evenStore", "0010_alter_cliente_apellidos_alter_cliente_clave_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="fechaNacimiento",
            field=models.DateField(db_column="FECHANACIMIENTO"),
        ),
    ]
