# Generated by Django 5.2 on 2025-05-07 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("E11evenStore", "0011_remove_administrativo_usuario"),
    ]

    operations = [
        migrations.AddField(
            model_name="compra",
            name="vendedor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ventas",
                to="E11evenStore.administrativo",
                to_field="rut",
                verbose_name="Vendedor responsable",
            ),
        ),
        migrations.AddField(
            model_name="detallecompra",
            name="vendedor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="E11evenStore.administrativo",
                to_field="rut",
                verbose_name="Vendedor",
            ),
        ),
    ]
